"""VARCH gate manifest (VARCH-10).

The single registry of the progressive CI gates the VARCH-0..9 slices contribute. Each gate is a
named, documented contract whose mechanism lives in a semantic module and whose enforcement lives
in a contract test. The manifest is SELF-VERIFYING: ``test_varch10_gate_manifest`` asserts every
``verify`` token actually appears in the gate's module/test source, so the registry can never
silently drift from the code. The ``scripts/gate_varch.py`` runner consumes this manifest to run
the gates progressively (slice order) with per-gate observability.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class GateSpec:
    """One progressive CI gate: a named contract, its module, and its enforcing test."""

    name: str
    slice: str
    module: str  # repo-relative path whose docstring documents the mechanism
    test: str  # repo-relative pytest path that enforces it
    contract: str
    # MANDATORY token that MUST appear in the gate's module+test source — the self-verification
    # mechanism that keeps the manifest from drifting from the code (no empty/structural escape).
    verify: str


# Progressive order: foundations first, then write-validation, binding, resolver, legacy, API.
SLICE_ORDER: tuple[str, ...] = (
    "VARCH-0",
    "VARCH-1",
    "VARCH-2",
    "VARCH-3",
    "VARCH-4a",
    "VARCH-4b",
    "VARCH-4c",
    "VARCH-4d",
    "VARCH-4e",
    "VARCH-4f",
    "VARCH-5a",
    "VARCH-5b",
    "VARCH-5c",
    "VARCH-5d",
    "VARCH-6a",
    "VARCH-6b",
    "VARCH-6c",
    "VARCH-6d",
    "VARCH-6e",
    "VARCH-6f",
    "VARCH-7",
    "VARCH-8a",
    "VARCH-8b",
    "VARCH-8c",
    "VARCH-8d",
    "VARCH-8e",
    "VARCH-9",
)

_T = "tests/"
_S = "src/semantic/"

VARCH_GATES: tuple[GateSpec, ...] = (
    # --- VARCH-0 profiles (foundational; verified by their conformance tests) -----------
    GateSpec(
        "canonical-serialization-profile",
        "VARCH-0",
        _S + "profiles/canonical_json.py",
        _T + "test_varch0_canonical_serialization.py",
        "Pinned canonical JSON serialization.",
        verify="sds-canonical-json-v1",
    ),
    GateSpec(
        "computation-profile",
        "VARCH-0",
        _S + "profiles/computation.py",
        _T + "test_varch0_computation_profile.py",
        "Deterministic decimal arithmetic profile.",
        verify="sds-computation-profile-v1",
    ),
    GateSpec(
        "profile-registry",
        "VARCH-0",
        _S + "profiles/registry.py",
        _T + "test_varch0_profile_registry.py",
        "Ratified profile registry + hashes.",
        verify="list_profiles",
    ),
    GateSpec(
        "conformance-corpus",
        "VARCH-0",
        _S + "profiles/computation.py",
        _T + "test_varch0_conformance_corpus.py",
        "Computation conformance vectors.",
        verify="fixture_corpus_sha256",
    ),
    # --- VARCH-1 migrations + ORM (foundational) ----------------------------------------
    GateSpec(
        "semantic-schema-decision-backbone",
        "VARCH-1",
        _S + "../database/semantic_models.py",
        _T + "test_varch1a_decision_backbone.py",
        "Fenced decision-commit backbone tables.",
        verify="decision_commit_sequence",
    ),
    GateSpec(
        "semantic-schema-vocabulary",
        "VARCH-1",
        _S + "../database/semantic_models.py",
        _T + "test_varch1b_vocabulary_layer.py",
        "Axes/terms/contracts vocabulary tables.",
        verify="semantic_axes",
    ),
    GateSpec(
        "semantic-schema-value-dims-bindings",
        "VARCH-1",
        _S + "../database/semantic_models.py",
        _T + "test_varch1c_value_dimensions_bindings.py",
        "Value-dimension + binding tables.",
        verify="value_context_dimensions",
    ),
    GateSpec(
        "semantic-schema-profile-registry",
        "VARCH-1",
        _S + "../database/semantic_models.py",
        _T + "test_varch1d_profile_registry.py",
        "Profile/manifest/schema registries.",
        verify="semantic_replay_manifests",
    ),
    GateSpec(
        "semantic-schema-factors-consolidation",
        "VARCH-1",
        _S + "../database/semantic_models.py",
        _T + "test_varch1e_factors_consolidation.py",
        "Factor sets + consolidation tables.",
        verify="semantic_factor_sets",
    ),
    GateSpec(
        "semantic-schema-evs-restatement-private",
        "VARCH-1",
        _S + "../database/semantic_models.py",
        _T + "test_varch1f_evs_restatement_tenant_private.py",
        "EVS/restatement/tenant-private tables.",
        verify="semantic_effective_version_sets",
    ),
    # --- VARCH-2 coverage ---------------------------------------------------------------
    GateSpec(
        "atomization-coverage-gate",
        "VARCH-2",
        _S + "coverage.py",
        _T + "test_varch2_coverage_gate.py",
        "Scope/tenant-aware bitemporal coverage denominator.",
        verify="atomization-coverage-gate",
    ),
    # --- VARCH-3 seed -------------------------------------------------------------------
    GateSpec(
        "varch0-seed-waste-plastic",
        "VARCH-3",
        _S + "../database/semantic_models.py",
        _T + "test_varch3_seed.py",
        "Seeded profiles + Waste_Plastic regression fixture.",
        verify="Waste_Plastic",
    ),
    # --- VARCH-4a temporal write-integrity ----------------------------------------------
    GateSpec(
        "temporal-window-integrity-gate",
        "VARCH-4a",
        _S + "write_temporal.py",
        _T + "test_varch4a_temporal_write_integrity.py",
        "tz-aware bounds; valid_to>valid_from.",
        verify="temporal-window-integrity-gate",
    ),
    GateSpec(
        "published-version-immutability-gate",
        "VARCH-4a",
        _S + "write_temporal.py",
        _T + "test_varch4a_temporal_write_integrity.py",
        "Published rows append-only.",
        verify="published-version-immutability-gate",
    ),
    GateSpec(
        "successor-publication-atomicity-gate",
        "VARCH-4a",
        _S + "write_temporal.py",
        _T + "test_varch4a_temporal_write_integrity.py",
        "Atomic supersede+insert plan.",
        verify="successor-publication-atomicity-gate",
    ),
    GateSpec(
        "write-skew-window-invariant-gate",
        "VARCH-4a",
        _S + "write_temporal.py",
        _T + "test_varch4a_temporal_write_integrity.py",
        "No published-sibling overlap.",
        verify="write-skew-window-invariant-gate",
    ),
    GateSpec(
        "bitemporal-reproducibility-gate",
        "VARCH-4a",
        _S + "write_temporal.py",
        _T + "test_varch4a_temporal_write_integrity.py",
        "Successor decision strictly later.",
        verify="bitemporal-reproducibility-gate",
    ),
    # --- VARCH-4b fenced sequencer ------------------------------------------------------
    GateSpec(
        "sequencer-continuity-gate",
        "VARCH-4b",
        _S + "write_sequencer.py",
        _T + "test_varch4b_fenced_sequencer.py",
        "previous==head; fork prevention.",
        verify="sequencer-continuity-gate",
    ),
    GateSpec(
        "decision-time-global-ordering-gate",
        "VARCH-4b",
        _S + "write_sequencer.py",
        _T + "test_varch4b_fenced_sequencer.py",
        "Monotonic global commit order.",
        verify="decision-time-global-ordering-gate",
    ),
    GateSpec(
        "decision-time-replay-gate",
        "VARCH-4b",
        _S + "write_sequencer.py",
        _T + "test_varch4b_fenced_sequencer.py",
        "Deterministic order replay.",
        verify="decision-time-replay-gate",
    ),
    # --- VARCH-4c replay/hashing --------------------------------------------------------
    GateSpec(
        "canonical-hash-serialization-gate",
        "VARCH-4c",
        _S + "write_replay.py",
        _T + "test_varch4c_replay_hashing.py",
        "Canonical content hashing.",
        verify="canonical-hash-serialization-gate",
    ),
    GateSpec(
        "computation-determinism-gate",
        "VARCH-4c",
        _S + "write_replay.py",
        _T + "test_varch4c_replay_hashing.py",
        "Value-level recomputation check.",
        verify="computation-determinism-gate",
    ),
    GateSpec(
        "profile-contract-backward-replay-gate",
        "VARCH-4c",
        _S + "write_replay.py",
        _T + "test_varch4c_replay_hashing.py",
        "Replay-manifest validation + pins.",
        verify="profile-contract-backward-replay-gate",
    ),
    GateSpec(
        "semantic-replay-manifest-gate",
        "VARCH-4c",
        _S + "write_replay.py",
        _T + "test_varch4c_replay_hashing.py",
        "Manifest schema + registry pins.",
        verify="semantic-replay-manifest-gate",
    ),
    # --- VARCH-4d private commitment ----------------------------------------------------
    GateSpec(
        "commitment-construction-replay-gate",
        "VARCH-4d",
        _S + "write_commitment.py",
        _T + "test_varch4d_private_commitment.py",
        "Deterministic HMAC commitment.",
        verify="commitment-construction-replay-gate",
    ),
    GateSpec(
        "commitment-key-replay-gate",
        "VARCH-4d",
        _S + "write_commitment.py",
        _T + "test_varch4d_private_commitment.py",
        "Key-lineage bound; shred fail-closed.",
        verify="commitment-key-replay-gate",
    ),
    GateSpec(
        "private-value-non-commitment-gate",
        "VARCH-4d",
        _S + "write_commitment.py",
        _T + "test_varch4d_private_commitment.py",
        "No private leak in projections.",
        verify="private-value-non-commitment-gate",
    ),
    # --- VARCH-4e disclosure ------------------------------------------------------------
    GateSpec(
        "aggregate-disclosure-control-gate",
        "VARCH-4e",
        _S + "write_disclosure.py",
        _T + "test_varch4e_disclosure.py",
        "k-anonymity suppression.",
        verify="aggregate-disclosure-control-gate",
    ),
    GateSpec(
        "suppression-outcome-replay-gate",
        "VARCH-4e",
        _S + "write_disclosure.py",
        _T + "test_varch4e_disclosure.py",
        "Deterministic suppression replay.",
        verify="suppression-outcome-replay-gate",
    ),
    GateSpec(
        "disclosure-profile-pin-gate",
        "VARCH-4e",
        _S + "write_disclosure.py",
        _T + "test_varch4e_disclosure.py",
        "Disclosure profile pin no-drift.",
        verify="disclosure-profile-pin-gate",
    ),
    GateSpec(
        "trace-existence-side-channel-gate",
        "VARCH-4e",
        _S + "write_disclosure.py",
        _T + "test_varch4e_disclosure.py",
        "Uniform redaction marker.",
        verify="trace-existence-side-channel-gate",
    ),
    GateSpec(
        "longitudinal-differencing-gate",
        "VARCH-4e",
        _S + "write_disclosure.py",
        _T + "test_varch4e_disclosure.py",
        "Complementary + adjacent-release stability.",
        verify="longitudinal-differencing-gate",
    ),
    # --- VARCH-4f scope/consolidation/license -------------------------------------------
    GateSpec(
        "tenant-scope-isolation-gate",
        "VARCH-4f",
        _S + "write_scope.py",
        _T + "test_varch4f_scope_consolidation_license.py",
        "Tenant-private visibility.",
        verify="tenant-scope-isolation-gate",
    ),
    GateSpec(
        "scope-transition-no-retroactive-exposure",
        "VARCH-4f",
        _S + "write_scope.py",
        _T + "test_varch4f_scope_consolidation_license.py",
        "No retroactive exposure.",
        verify="scope-transition-no-retroactive-exposure",
    ),
    GateSpec(
        "cross-tenant-consolidation-authorization-gate",
        "VARCH-4f",
        _S + "write_scope.py",
        _T + "test_varch4f_scope_consolidation_license.py",
        "Every member consents.",
        verify="cross-tenant-consolidation-authorization-gate",
    ),
    GateSpec(
        "consolidation-composition-profile-gate",
        "VARCH-4f",
        _S + "write_scope.py",
        _T + "test_varch4f_scope_consolidation_license.py",
        "Fail-closed most-restrictive composition.",
        verify="consolidation-composition-profile-gate",
    ),
    GateSpec(
        "license-rights-temporal-window-gate",
        "VARCH-4f",
        _S + "write_scope.py",
        _T + "test_varch4f_scope_consolidation_license.py",
        "License window/expiry/revocation.",
        verify="license-rights-temporal-window-gate",
    ),
    GateSpec(
        "license-aware-egress-gate",
        "VARCH-4f",
        _S + "write_scope.py",
        _T + "test_varch4f_scope_consolidation_license.py",
        "Egress gated by access/rights ceiling.",
        verify="license-aware-egress-gate",
    ),
    # --- VARCH-5 binding/calculation/EVS ------------------------------------------------
    GateSpec(
        "source-rights",
        "VARCH-5a",
        _S + "write_binding.py",
        _T + "test_varch5a_sygris_binding.py",
        "Binding source-rights pin.",
        verify="source-rights",
    ),
    GateSpec(
        "slice-coverage",
        "VARCH-5a",
        _S + "write_binding.py",
        _T + "test_varch5a_sygris_binding.py",
        "Bound subject is covered.",
        verify="slice-coverage",
    ),
    GateSpec(
        "mapping-component-binding",
        "VARCH-5b",
        _S + "write_binding.py",
        _T + "test_varch5b_mapping_component_binding.py",
        "Term-belongs-to-axis binding.",
        verify="validate_mapping_component_binding",
    ),
    GateSpec(
        "factor-vintage-selection",
        "VARCH-5c",
        _S + "write_binding.py",
        _T + "test_varch5c_calculation_binding.py",
        "Calc pins resolve to live state.",
        verify="factor-vintage-selection",
    ),
    GateSpec(
        "effective-version-set-equivalence",
        "VARCH-5d",
        _S + "write_evs.py",
        _T + "test_varch5d_evs_assembly.py",
        "EVS digest binds identity+members.",
        verify="effective-version-set-equivalence",
    ),
    GateSpec(
        "version-pin-reproducibility",
        "VARCH-5d",
        _S + "write_evs.py",
        _T + "test_varch5d_evs_assembly.py",
        "Members resolve to published versions.",
        verify="version-pin-reproducibility",
    ),
    GateSpec(
        "slice-coverage-completeness",
        "VARCH-5d",
        _S + "write_evs.py",
        _T + "test_varch5d_evs_assembly.py",
        "No missing/stranded subjects.",
        verify="slice-coverage-completeness",
    ),
    # --- VARCH-6 resolver ---------------------------------------------------------------
    GateSpec(
        "decision-time-membership",
        "VARCH-6a",
        _S + "resolver.py",
        _T + "test_varch6a_resolution_context.py",
        "Read decision is a committed member.",
        verify="decision-time-membership",
    ),
    GateSpec(
        "evs-selection-pin",
        "VARCH-6a",
        _S + "resolver.py",
        _T + "test_varch6a_resolution_context.py",
        "Exactly one valid EVS or SNAPSHOT_REQUIRED.",
        verify="evs-selection-pin",
    ),
    GateSpec(
        "publication-chain-integrity",
        "VARCH-6a",
        _S + "resolver.py",
        _T + "test_varch6a_resolution_context.py",
        "No overlap/gap-at-slice.",
        verify="publication-chain-integrity",
    ),
    GateSpec(
        "relation-graph-integrity",
        "VARCH-6a",
        _S + "resolver.py",
        _T + "test_varch6a_resolution_context.py",
        "In-slice edges + acyclic.",
        verify="relation-graph-integrity",
    ),
    GateSpec(
        "read-scope-authorization",
        "VARCH-6b",
        _S + "resolver_disclosure.py",
        _T + "test_varch6b_disclosure_resolution.py",
        "Steward/scope auth.",
        verify="read-scope-authorization",
    ),
    GateSpec(
        "disclosure-pin-reproducibility",
        "VARCH-6b",
        _S + "resolver_disclosure.py",
        _T + "test_varch6b_disclosure_resolution.py",
        "Pinned suppression reproduced.",
        verify="disclosure-pin-reproducibility",
    ),
    GateSpec(
        "composed-outcome-reproducibility",
        "VARCH-6b",
        _S + "resolver_disclosure.py",
        _T + "test_varch6b_disclosure_resolution.py",
        "Composed consolidation reproduced.",
        verify="composed-outcome-reproducibility",
    ),
    GateSpec(
        "deterministic-factor-vintage-selection",
        "VARCH-6c",
        _S + "resolver_factors.py",
        _T + "test_varch6c_factor_resolution.py",
        "Total deterministic vintage pick.",
        verify="deterministic-factor-vintage-selection",
    ),
    GateSpec(
        "factor-source-rights",
        "VARCH-6c",
        _S + "resolver_factors.py",
        _T + "test_varch6c_factor_resolution.py",
        "Provenance-bound license.",
        verify="factor-source-rights",
    ),
    GateSpec(
        "partition-MECE-closure",
        "VARCH-6d",
        _S + "resolver_evaluate.py",
        _T + "test_varch6d_evaluation.py",
        "Mutually-exclusive + exhaustive partition.",
        verify="partition-MECE-closure",
    ),
    GateSpec(
        "dimension-collapse-decision",
        "VARCH-6d",
        _S + "resolver_evaluate.py",
        _T + "test_varch6d_evaluation.py",
        "Collapse tree fail-closed.",
        verify="dimension-collapse-decision",
    ),
    GateSpec(
        "confidence-composition",
        "VARCH-6d",
        _S + "resolver_evaluate.py",
        _T + "test_varch6d_evaluation.py",
        "Versioned hash-pinned confidence.",
        verify="confidence-composition",
    ),
    GateSpec(
        "outbox-projection-safety",
        "VARCH-6e",
        _S + "resolver_outbox.py",
        _T + "test_varch6e_outbox.py",
        "Scope/disclosure/license-aware outbox.",
        verify="outbox-projection-safety",
    ),
    GateSpec(
        "private-payload-authorization",
        "VARCH-6e",
        _S + "resolver_outbox.py",
        _T + "test_varch6e_outbox.py",
        "Tenant auth + erasure fail-closed.",
        verify="private-payload-authorization",
    ),
    GateSpec(
        "trace-pin-completeness",
        "VARCH-6f",
        _S + "resolver_trace.py",
        _T + "test_varch6f_trace_pins.py",
        "All required trace pins present.",
        verify="trace-pin-completeness",
    ),
    GateSpec(
        "trace-hash-reproducibility",
        "VARCH-6f",
        _S + "resolver_trace.py",
        _T + "test_varch6f_trace_pins.py",
        "Content-addressed trace.",
        verify="trace-hash-reproducibility",
    ),
    # --- VARCH-7 legacy -----------------------------------------------------------------
    GateSpec(
        "legacy-classification-determinism",
        "VARCH-7",
        _S + "legacy_dimensions.py",
        _T + "test_varch7a_legacy_classification.py",
        "Deterministic 4-state classification.",
        verify="legacy-classification-determinism",
    ),
    GateSpec(
        "legacy-classification-content-address",
        "VARCH-7",
        _S + "legacy_dimensions.py",
        _T + "test_varch7a_legacy_classification.py",
        "Content-addressed classification.",
        verify="legacy-classification-content-address",
    ),
    GateSpec(
        "legacy-dimensions-audit",
        "VARCH-7",
        _S + "legacy_dimensions.py",
        _T + "test_varch7b_legacy_policy.py",
        "Sample-verify classification quality.",
        verify="legacy-dimensions-audit",
    ),
    # --- VARCH-8 read API ---------------------------------------------------------------
    GateSpec(
        "tenant-scope-isolation",
        "VARCH-8a",
        _S + "read_scope.py",
        _T + "test_varch8a_read_scope.py",
        "Centralized read scope filter.",
        verify="tenant-scope-isolation",
    ),
    GateSpec(
        "public-projection-privacy",
        "VARCH-8a",
        _S + "read_scope.py",
        _T + "test_varch8a_read_scope.py",
        "No private field in projection.",
        verify="public-projection-privacy",
    ),
    GateSpec(
        "cursor-tamper-evidence",
        "VARCH-8b",
        _S + "read_cursor.py",
        _T + "test_varch8b_read_cursor.py",
        "HMAC cursor fails closed.",
        verify="cursor-tamper-evidence",
    ),
    GateSpec(
        "cursor-no-silent-advance",
        "VARCH-8b",
        _S + "read_cursor.py",
        _T + "test_varch8b_read_cursor.py",
        "Supersession pinned/stale.",
        verify="cursor-no-silent-advance",
    ),
    GateSpec(
        "resolver-read-input-materialization",
        "VARCH-8c",
        _S + "../services/resolver_read.py",
        _T + "test_varch8c_resolver_read.py",
        "Load+map+call resolver cores.",
        verify="resolver-read-input-materialization",
    ),
    GateSpec(
        "resolved-version-index-fail-closed",
        "VARCH-8c",
        _S + "../services/resolver_read.py",
        _T + "test_varch8c_resolver_read.py",
        "Unwired kind fails closed.",
        verify="resolved-version-index-fail-closed",
    ),
    GateSpec(
        "semantic-dimensions-catalog-read",
        "VARCH-8d",
        _S + "../services/semantic_catalog.py",
        _T + "test_varch8d_catalog_repo.py",
        "Published-axes bitemporal catalog read.",
        verify="list_published_axes",
    ),
    GateSpec(
        "semantic-dimensions-endpoint",
        "VARCH-8d",
        _S + "../api/routers/semantic_dimensions.py",
        _T + "test_varch8d_semantic_dimensions_api.py",
        "Endpoint with selectors+pins+cursor.",
        verify="response_pins",
    ),
    GateSpec(
        "concepts-temporal-selectors",
        "VARCH-8e",
        _S + "../api/routers/ontology.py",
        _T + "test_varch8e_concepts_selectors.py",
        "Backward-compatible /concepts selectors.",
        verify="_concepts_temporal_pins",
    ),
    GateSpec(
        "openapi-temporal-read-docs",
        "VARCH-9",
        _S + "../api/openapi_docs.py",
        _T + "test_varch9_openapi_docs.py",
        "Swagger examples for the endpoints.",
        verify="semantic-dimensions",
    ),
)


def gates_by_slice() -> dict[str, list[GateSpec]]:
    """Gates grouped by slice, in progressive SLICE_ORDER."""
    grouped: dict[str, list[GateSpec]] = {s: [] for s in SLICE_ORDER}
    for gate in VARCH_GATES:
        grouped.setdefault(gate.slice, []).append(gate)
    return grouped
