#!/usr/bin/env python3
"""Import a register-first Atomizer package into SDS through the canonical indicator importer."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
IMPORT_SCRIPT = REPO_ROOT / "api" / "scripts" / "import_indicators.py"
PACKAGE_DIR_ENV = "ATOMIZER_SDS_PACKAGE_DIR"
REGISTER_FILENAME = "sds_dataset_register.csv"
SERVICE_VENV_PYTHONS = (
    REPO_ROOT / "api" / ".venv" / "Scripts" / "python.exe",
    REPO_ROOT / "api" / ".venv" / "bin" / "python",
)


def resolve_register_csv(package_dir: Path, explicit_csv: Path | None) -> Path:
    if explicit_csv is not None:
        if explicit_csv.exists():
            return explicit_csv.resolve()
        candidate = (REPO_ROOT / explicit_csv).resolve()
        if candidate.exists():
            return candidate
        return explicit_csv
    return (package_dir / REGISTER_FILENAME).resolve()


def resolve_python_executable() -> str:
    for candidate in SERVICE_VENV_PYTHONS:
        if candidate.exists():
            return str(candidate)
    return sys.executable


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Import indicators directly from an Atomizer register-first package."
    )
    parser.add_argument(
        "--package-dir",
        type=Path,
        default=Path(os.environ[PACKAGE_DIR_ENV]) if os.environ.get(PACKAGE_DIR_ENV) else None,
        help=f"Path to an SDS package generated by Atomizer. Also accepted via {PACKAGE_DIR_ENV}.",
    )
    parser.add_argument("--csv", type=Path, default=None, help="Explicit register CSV path")
    parser.add_argument("--db-url", type=str, default=None)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--batch-size", type=int, default=None)
    args = parser.parse_args(argv)

    if args.package_dir is None and args.csv is None:
        print(
            f"FAIL: --package-dir or --csv is required unless {PACKAGE_DIR_ENV} is set.",
            file=sys.stderr,
        )
        return 1

    package_dir = args.package_dir.resolve() if args.package_dir is not None else REPO_ROOT
    register_csv = resolve_register_csv(package_dir, args.csv)
    if not register_csv.exists():
        print(f"FAIL: register CSV not found: {register_csv}", file=sys.stderr)
        return 1

    command = [resolve_python_executable(), str(IMPORT_SCRIPT), "--csv", str(register_csv)]
    if args.db_url:
        command.extend(["--db-url", args.db_url])
    if args.dry_run:
        command.append("--dry-run")
    if args.resume:
        command.append("--resume")
    if args.batch_size is not None:
        command.extend(["--batch-size", str(args.batch_size)])

    return subprocess.call(command, cwd=str(REPO_ROOT))


if __name__ == "__main__":
    raise SystemExit(main())
