#!/usr/bin/env python3
"""Compatibility wrapper for the hardened complete Atomizer package importer."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
FULL_PACKAGE_IMPORT_SCRIPT = REPO_ROOT / "scripts" / "import_atomizer_sds_package.py"
PACKAGE_DIR_ENV = "ATOMIZER_SDS_PACKAGE_DIR"
REGISTER_FILENAME = "sds_dataset_register.csv"
IMPORT_SUBPROCESS_TIMEOUT_SECONDS = 30 * 60
SERVICE_VENV_PYTHONS = (
    REPO_ROOT / "api" / ".venv" / "Scripts" / "python.exe",
    REPO_ROOT / "api" / ".venv" / "bin" / "python",
)


def resolve_register_csv(package_dir: Path, explicit_csv: Path | None) -> Path:
    if explicit_csv is not None:
        return explicit_csv if explicit_csv.is_absolute() else REPO_ROOT / explicit_csv
    return package_dir / REGISTER_FILENAME


def resolve_python_executable() -> str:
    for candidate in SERVICE_VENV_PYTHONS:
        if candidate.exists():
            return str(candidate)
    return sys.executable


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Import indicators from a complete Atomizer package through the "
            "hardened package intake."
        )
    )
    parser.add_argument(
        "--package-dir",
        type=Path,
        default=Path(os.environ[PACKAGE_DIR_ENV]) if os.environ.get(PACKAGE_DIR_ENV) else None,
        help=f"Path to an SDS package generated by Atomizer. Also accepted via {PACKAGE_DIR_ENV}.",
    )
    parser.add_argument("--csv", type=Path, default=None, help="Explicit register CSV path")
    parser.add_argument("--db-url", type=str, default=None)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--batch-size", type=int, default=None)
    args = parser.parse_args(argv)

    if args.package_dir is None:
        print(
            f"FAIL: --package-dir is required unless {PACKAGE_DIR_ENV} is set; "
            "CSV-only imports are not a supported trust boundary.",
            file=sys.stderr,
        )
        return 1

    command = [
        resolve_python_executable(),
        str(FULL_PACKAGE_IMPORT_SCRIPT),
        "--package-dir",
        str(args.package_dir),
        "--skip-standard-versioning",
        "--skip-calculation-contract",
        "--skip-values",
    ]
    if args.csv is not None:
        command.extend(["--register-csv", str(args.csv)])
    if args.db_url:
        command.extend(["--db-url", args.db_url])
    if args.dry_run:
        command.append("--dry-run")
    if args.resume:
        command.append("--resume")
    if args.batch_size is not None:
        command.extend(["--batch-size", str(args.batch_size)])

    try:
        return subprocess.call(
            command,
            cwd=str(REPO_ROOT),
            timeout=IMPORT_SUBPROCESS_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired:
        print("FAIL: hardened Atomizer package import timed out.", file=sys.stderr)
        return 1
    except OSError as exc:
        print(
            f"FAIL: hardened Atomizer package import could not start: {type(exc).__name__}",
            file=sys.stderr,
        )
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
